In [ ]:
import tensorflow as tf
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data(path="mnist.npz")


11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [ ]:
x_train=x_train/255
x_test=x_test/255

(28, 28)

In [ ]:

from tensorflow import keras

model = keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=x_train[0].shape))
model.add(tf.keras.layers.Dense(532,activation ='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

In [ ]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

In [ ]:
history = model.fit(x_train,y_train,epochs = 30)

Epoch 1/30
1875/1875 [==============================] - 6s 2ms/step - loss: 0.2019 - accuracy: 0.9396
Epoch 2/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0802 - accuracy: 0.9751
Epoch 3/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0517 - accuracy: 0.9841
Epoch 4/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0362 - accuracy: 0.9884
Epoch 5/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0264 - accuracy: 0.9918
Epoch 6/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0215 - accuracy: 0.9929
Epoch 7/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0177 - accuracy: 0.9945
Epoch 8/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0136 - accuracy: 0.9954
Epoch 9/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0132 - accuracy: 0.9957
Epoch 10/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.010

In [ ]:
model.get_weights()

[array([[ 6.3647859e-02, -1.7463714e-03,  2.9181153e-02, ...,
         -5.9110940e-02, -3.8746338e-02,  5.7507820e-02],
        [ 4.5159757e-02, -6.2126413e-02, -6.1966103e-02, ...,
         -1.1427276e-02,  3.0148305e-02,  2.9122412e-02],
        [ 2.7364343e-02,  5.1629864e-02,  2.1249056e-05, ...,
          3.4329854e-02,  1.5454516e-03, -4.5722790e-02],
        ...,
        [-4.9732126e-02,  5.8522895e-03,  1.2396313e-02, ...,
         -3.0991793e-02,  1.7037570e-02, -3.2448024e-02],
        [ 5.4543830e-02,  6.2166370e-02, -5.9908621e-02, ...,
         -2.2888552e-02, -2.8398003e-02,  2.1190889e-02],
        [-6.5191038e-02, -2.6766203e-02,  2.5982335e-03, ...,
         -5.7822891e-02, -3.9559573e-02, -6.2547259e-02]], dtype=float32),
 array([-0.00853381, -0.02987956, -0.11477605, -0.04667534,  0.05020574,
         0.20097722, -0.04725198, -0.1454657 , -0.00160439,  0.04314984,
         0.11239532, -0.06669067, -0.20760117, -0.13636358, -0.02360099,
        -0.08367825, -0.0267593

In [ ]:
import numpy as np
y_pred = np.argmax(model.predict(x_test),axis=1)
y_pred

array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9834

In [ ]:
model.save('digitsmnist.hdf5')